- hosts: local
  tasks:
  - name: Download uTorrent
    get_url: url=http://download-new.utorrent.com/endpoint/utserver/os/linux-x64-ubuntu-13-04/track/beta/ dest=/tmp/utserver.tar.gz
  - name: Extract uTorrent to /opt/
    unarchive: src=/tmp/utserver.tar.gz dest=/opt/ copy=no
  - name: Ensure uTserver has the correct permissions
    file: path=/opt/utorrent-server-alpha-v3_3 mode=0777 recurse=yes
  - name: Create symlink for uTorrent
    file: src=/opt/utorrent-server-alpha-v3_3/utserver dest=/usr/bin/utserver state=link
  - name: Get uTorrent start script
    get_url: url=https://raw.githubusercontent.com/gizlonk/HTPC/master/files/utorrent dest=/etc/init.d/utorrent
  - name: Set Permissions for /etc/init.d/utorrent
    file: path=/etc/init.d/utorrent mode=0755
  - name: Make uTorrent startupable
    shell: update-rc.d utorrent defaults
